### ISSUE TITLE
Code availability

### ISSUE THREAD

**Issue by ktroule** [gambalab/CloneTrackerXP_exstraction#1]
Hi.

Is the code for CloneTracker XP barcode retrieval available [paper](https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-024-01327-2).

Thanks

**Comment by ktroule** [comment]
Hi, @gambalab.

In case the message hasn't been read.

Regards

**Comment by gambalab** [comment]
Sorry for late response.. but the email associated to this repo is an mail that I never open. Anyway, I just added the code, although I have no time to comment it more than this.

Regards,
GG
